apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devportal-pvc
  namespace: registry-test
spec:
  storageClassName: local-storage
  volumeName: devportal-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
