apiVersion: v1
kind: PersistentVolume
metadata:
  name: devportal-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  hostPath:
    path: "/mnt/data"

