apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devportal-pvc
spec:
  storageClassName: local-storage
  volumeName: devportal-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
