apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployer-rb
subjects:
  - kind: ServiceAccount
    name: deployer-sa
    namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: deployer-r
  apiGroup: rbac.authorization.k8s.io
