apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kamrad-deploy
spec:
  workspaces:
    - name: code
      description: The workspace where the dev portal source code resides
      mountPath: /workspace/code
    - name: devportal
      description: The workspace where the dev portal final html code resides
      mountPath: /workspace/devportal
  steps:
    - name: deploy
      image: quay.io/didierofrivia/spec-builder:latest
      workingDir: /workspace/
      script: |
        echo "Deploy..."
        echo "cp -vR /workspace/code/public/* /workspace/devportal/"
        cp -vR /workspace/code/public/* /workspace/devportal/
